# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='python', max_length=200),
            preserve_default=False,
        ),
    ]
