# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160803_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.TextField(verbose_name='Tag'),
        ),
    ]
