# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160803_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tags',
            new_name='post',
        ),
    ]
