# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160803_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
    ]
